# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mMggTTtpE0xI4_24TUOIOIpO1RMFrrH

Dictionary in python
"""

artist = {
    "name" : "Taylor Swift" ,
    "age" : 31 ,
    "type" : "Singer"
}
print(artist)
print(type(artist))

student = {
    "name" : "Trisha Bajpai" ,
    "age" : 18 ,
    "course" : "Bsc-economics"
}
print(student)
print(type(student))

print(student['course'])
print(student['age'])
print(student['name'])

student["age"] = 20
print(student)

student["hobby"] = "listening to music"
print(student)

from os import remove
student.pop("hobby")
print(student)

print(student.keys())
print(student.values())

"""grocery store"""

print("Welcome to trisha's mart")
print("="*35)
#shopkeepers side
store = {
    "rice" : 60 ,
    "wheat" : 60 ,
    "milk" : 25 ,
    "oil" : 35 ,
    "eggs" : 50
}
print("Thats all i got")
print(store)
print("="*60)
#customers side
print("What do you want to buy")
item_to_buy = input("Tell me what do you want ")
qty = int(input("Tell me how much you want "))
print("i want", item_to_buy , qty , "Quantity")
#bill
print("="*40)
price = store[item_to_buy]
total = price * qty
print("YOUR BILL IS" , total)





