# -*- coding: utf-8 -*-
"""Lists-11/12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUCsp161w9CXj4-9TvtXvXT-lE5hlrFa
"""

print("check")

#list of roll numbers- it is a comment not a code

my_list = [ 101 , 102 , 103 , 104 ]
print(my_list)

"""list operations

what all things we can do with list

first- append (adding new items to list to the end)
"""

my_list.append(105)
print(my_list)

"""second- insert (add new items on specific location)

location python uses starts counting from 0
"""

my_list.insert(2 , 109)
print(my_list)

"""third- pop() (remove items from the list at the end)

"""

my_list.pop()
print(my_list)

my_list.pop()
print(my_list)

"""fourth- remove(specifically remove something, exactly specify)"""

my_list.remove(109)
print(my_list)

"""now make shopping cart"""

from os import remove
print("WeELCOME TO SSE MART")
print("=" * 20)

shopping_cart = ["pizza" ,"burger" ,"chips" , "books" , "games" ]
print(shopping_cart)
print("=" * 40)

add_item = "uniform"
shopping_cart.append(add_item)
print(shopping_cart)
print("=" * 50)

remove_item = "books"
shopping_cart.remove(remove_item)
print(shopping_cart)
print("=" * 50)

print("WELCOME TO Trisha's Playlist")
print("=" * 20)

liked_songs = ["night changes","what makes you beautiful" ,"baby" , "belong together" , "all around the world" ]
print(liked_songs)
print("=" * 80)

add_item = "strong"
liked_songs.append(add_item)
print(liked_songs)
print("=" * 100)

add_item = "perfect"
liked_songs.append(add_item)
print(liked_songs)
print("=" * 115)

remove_item = "baby"
liked_songs.remove(remove_item)
print(liked_songs)
print("=" * 110)

