# -*- coding: utf-8 -*-
"""python day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBny-GKA_pJhP-mZ_ioWA1RzSyFtqTeY

shift+enter--next line
control+enter--same line
"""

population = 32443546346748734
print(population)

## variable

unemployment_rate = 36
print(unemployment_rate)

years_until_2030 = 2030-2025
print(years_until_2030)

type(years_until_2030)

"""float
decimal points
"""

inflation_rate = 5.42
gdp_growth = 6.3
print("The inflation rate is = " , inflation_rate)

"""3. string
text
"""

name = "Trisha"
print(name)
print("My name is" , name)

type(name)

"""LIST

List of values separated by commas

mutable
"""

foods = ["pasta" , "chole bhature" , 18 , 8.5 ]
print(foods)

type(foods)

"""how list solves the problems"""

numbers = [346, 351 , 268 , 100 , 89 , 496 , 110 ]
print(numbers)
numbers.append(69)
print(numbers)
numbers.pop()
print(numbers)
numbers.pop(4)
print(numbers)

print(sorted(numbers))

"""TUPLES-
immutable
"""

number = (1 , 6 , 89 , "hi" , 3.7 )
print(number)

type(number)





