# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFVAXXdcDhti7NTvTVIuViYUvGKn5SfE
"""

!pip install streamlit pillow
import streamlit as st
from PIL import Image
import time
import base64
from pathlib import Path

st.set_page_config(
    page_title="Happy Birthday Aashka ❤️",
    page_icon="🎂",
    layout="centered"
)

# -----------------------
# CUSTOM CSS
# -----------------------

st.markdown("""
<style>

html, body, [class*="css"]{
    font-family: 'Poppins', sans-serif;
    background:#FFF8FB;
}

.main{
    background:#FFF8FB;
}

.title{
    text-align:center;
    font-size:52px;
    font-weight:bold;
    color:#ff4f81;
    margin-top:40px;
}

.subtitle{
    text-align:center;
    font-size:24px;
    color:#444;
}

button[kind="primary"]{
    background:#ff4f81;
    border:none;
    border-radius:15px;
    height:55px;
    width:250px;
    font-size:20px;
}

.typewriter{
    font-size:22px;
    line-height:2;
    white-space:pre-wrap;
}

img{
    border-radius:20px;
}

</style>
""", unsafe_allow_html=True)

# -----------------------
# SESSION STATE
# -----------------------

if "page" not in st.session_state:
    st.session_state.page = 0

# -----------------------
# LOADING PAGE
# -----------------------

if st.session_state.page == 0:

    st.markdown("<div class='title'>✨ Loading your surprise... ✨</div>",
                unsafe_allow_html=True)

    st.progress(0)

    progress = st.empty()

    for i in range(100):

        progress.progress(i+1)

        time.sleep(0.02)

    st.session_state.page = 1

    st.rerun()

# -----------------------
# PAGE 1
# -----------------------

elif st.session_state.page == 1:

    st.markdown("<div class='title'>Hey Aashka! ✨</div>",
                unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    st.markdown(
        "<div class='subtitle'>Someone has a little surprise waiting for you...❤️</div>",
        unsafe_allow_html=True)

    st.write("")

    st.write("")

    c1,c2,c3 = st.columns([1,2,1])

    with c2:

        if st.button("🎁 Open Surprise",use_container_width=True):

            st.session_state.page = 2

            st.rerun()

# -----------------------
# PAGE 2
# -----------------------

elif st.session_state.page == 2:

    st.markdown(
    "<div class='title'>Are you ready for your surprise? 🥹❤️</div>",
    unsafe_allow_html=True)

    st.write("")
    st.write("")

    c1,c2 = st.columns(2)

    with c1:

        if st.button("Yes! ❤️",use_container_width=True):

            st.session_state.page = 3

            st.rerun()

    with c2:

        if st.button("Definitely Yes!! 💕",use_container_width=True):

            st.balloons()

            time.sleep(1)

            st.session_state.page = 3

            st.rerun()


# -----------------------
# PAGE 3
# -----------------------

elif st.session_state.page == 3:

    st.balloons()

    st.markdown("""
    <h1 style='text-align:center;
               color:#ff4f81;
               font-size:60px;'>
    Happyy Birthdayy
    </h1>
    """, unsafe_allow_html=True)

    st.markdown("""
    <h1 style='text-align:center;
               color:#ff4f81;
               font-size:48px;'>
    Aashka ❤️❤️❤️
    </h1>
    """, unsafe_allow_html=True)

    st.write("")
    time.sleep(2)

    st.session_state.page = 4
    st.rerun()


# -----------------------
# PAGE 4
# -----------------------

elif st.session_state.page == 4:

    st.markdown("""
    <h2 style='text-align:center;
               color:#ff4f81;'>
    💌
    </h2>
    """, unsafe_allow_html=True)

    message = """
Happyy Birthdayy Aashka❤️❤️❤️

Thank you for always being there, hamesha meri bakwaas sunne ke liye and for all the random nonsense we talk about... (shush🤫)

I honestly don't know how I would've survived 11th and 12th if tu starting mein mere paas na aayi hoti.

I still remember you saying,
"Tu hamesha front mein kyun baithti hai?"
and me just being like... 🤷‍♀️😂

Haan, ab hum saath nahi baithte like the old days,
aur daily bhi nahi milte.

But the bond we share is still exactly the same...
it's only getting stronger. ❤️

You'll always be the first person I tell everything to.
No matter what happens,
you'll always have that special place in my life. 😘😘

Aur haan,
yaad hai na...

mere marne ke baad mera pati bhi chori karna hai.

Extra marital affair pakka! 🤣🤣

(Waise bhi mera pati teri pasand ka hi hoga. 😂😂)

Bas...
ab aur kuch yaad nahi aa raha mujhe. 😭😭

Thaaaaannnnkkkkkk Youuuuuu
for being the amazing and crazy person you are.

A Veryyyy Happyyyy Birthdayyyy Darlinggg!! ❤️❤️😘😘

Lavvvv youuuu❤️

Mwahhh💋💋😘😘
"""

    placeholder = st.empty()

    text = ""

    for letter in message:
        text += letter
        placeholder.markdown(
            f"""
<div style="
font-size:22px;
line-height:2;
color:#333;
white-space:pre-wrap;
font-family:Poppins;">
{text}<span style="color:#ff4f81;">|</span>
</div>
""",
            unsafe_allow_html=True,
        )
        time.sleep(0.02)

    st.write("")
    st.write("")

    c1, c2, c3 = st.columns([1, 2, 1])

    with c2:

        st.success("❤️ Happy Birthday once again! ❤️")


# -----------------------
# PAGE 5
# -----------------------

elif st.session_state.page == 5:

    st.balloons()

    st.markdown("""
    <h1 style='text-align:center;
               color:#ff4f81;'>
    ❤️ The End ❤️
    </h1>
    """, unsafe_allow_html=True)

